// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechMod.Data;

#nullable disable

namespace TechMod.Migrations
{
    [DbContext(typeof(InfoDB))]
    partial class InfoDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("TechMod.Data.InfoDB+ChannelMute", b =>
                {
                    b.Property<int>("ChannelMuteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BeginTime")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("Channel")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("Guild")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("LockMessage")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("No")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UnmuteTime")
                        .HasColumnType("TEXT");

                    b.Property<ushort>("Yes")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChannelMuteId");

                    b.ToTable("ChannelMute");
                });

            modelBuilder.Entity("TechMod.Data.InfoDB+GuildSettings", b =>
                {
                    b.Property<int>("GuildSettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("Guild")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("MinimumToConsider")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TiePriority")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("VoteRole")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildSettingsId");

                    b.ToTable("GuildSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
